#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/FG2.filtered.paired.1.fq.gz -2 /home/knam/work/fq/FG2.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FG2.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FG2.sorted.bam FG2.raw.bam

rm FG2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FG2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FG2.sorted.bam OUTPUT=FG2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FG2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FG2
rm FG2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FG2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FG2.dupl_rm.bam OUTPUT=FG2.bam RGID=FG2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FG2;

rm -rf temp.FG2
rm FG2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FG2.bam
/home/knam/save/programs/samtools-1.9/samtools stats FG2.bam > FG2.stats
