#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/G_2.3.filtered.paired.1.fq.gz -2 /home/knam/work/fq/G_2.3.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/G_2.3.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o G_2.3.sorted.bam G_2.3.raw.bam

rm G_2.3.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.G_2.3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=G_2.3.sorted.bam OUTPUT=G_2.3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=G_2.3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.G_2.3
rm G_2.3.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.G_2.3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=G_2.3.dupl_rm.bam OUTPUT=G_2.3.bam RGID=G_2.3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=G_2.3;

rm -rf temp.G_2.3
rm G_2.3.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index G_2.3.bam
/home/knam/save/programs/samtools-1.9/samtools stats G_2.3.bam > G_2.3.stats
