#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/PR12.filtered.paired.1.fq.gz -2 /home/knam/work/fq/PR12.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/PR12.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o PR12.sorted.bam PR12.raw.bam

rm PR12.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR12 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR12.sorted.bam OUTPUT=PR12.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR12.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.PR12
rm PR12.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR12 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR12.dupl_rm.bam OUTPUT=PR12.bam RGID=PR12 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR12;

rm -rf temp.PR12
rm PR12.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index PR12.bam
/home/knam/save/programs/samtools-1.9/samtools stats PR12.bam > PR12.stats
