#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/PR1.filtered.paired.1.fq.gz -2 /home/knam/work/fq/PR1.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/PR1.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o PR1.sorted.bam PR1.raw.bam

rm PR1.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR1 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR1.sorted.bam OUTPUT=PR1.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR1.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.PR1
rm PR1.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR1 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR1.dupl_rm.bam OUTPUT=PR1.bam RGID=PR1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR1;

rm -rf temp.PR1
rm PR1.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index PR1.bam
/home/knam/save/programs/samtools-1.9/samtools stats PR1.bam > PR1.stats
