#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/FG4.filtered.paired.1.fq.gz -2 /home/knam/work/fq/FG4.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FG4.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FG4.sorted.bam FG4.raw.bam

rm FG4.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FG4 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FG4.sorted.bam OUTPUT=FG4.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FG4.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FG4
rm FG4.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FG4 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FG4.dupl_rm.bam OUTPUT=FG4.bam RGID=FG4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FG4;

rm -rf temp.FG4
rm FG4.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FG4.bam
/home/knam/save/programs/samtools-1.9/samtools stats FG4.bam > FG4.stats
