#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/PR31.filtered.paired.1.fq.gz -2 /home/knam/work/fq/PR31.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/PR31.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o PR31.sorted.bam PR31.raw.bam

rm PR31.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR31 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR31.sorted.bam OUTPUT=PR31.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR31.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.PR31
rm PR31.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR31 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR31.dupl_rm.bam OUTPUT=PR31.bam RGID=PR31 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR31;

rm -rf temp.PR31
rm PR31.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index PR31.bam
/home/knam/save/programs/samtools-1.9/samtools stats PR31.bam > PR31.stats
