#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/PR5.filtered.paired.1.fq.gz -2 /home/knam/work/fq/PR5.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/PR5.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o PR5.sorted.bam PR5.raw.bam

rm PR5.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR5 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR5.sorted.bam OUTPUT=PR5.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR5.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.PR5
rm PR5.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.PR5 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR5.dupl_rm.bam OUTPUT=PR5.bam RGID=PR5 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR5;

rm -rf temp.PR5
rm PR5.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index PR5.bam
/home/knam/save/programs/samtools-1.9/samtools stats PR5.bam > PR5.stats
