#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2  --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/fq/FL.19.filtered.paired.1.fq.gz -2 /home/knam/work/fq/FL.19.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FL.19.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FL.19.sorted.bam FL.19.raw.bam

rm FL.19.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FL.19 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FL.19.sorted.bam OUTPUT=FL.19.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FL.19.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FL.19
rm FL.19.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FL.19 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FL.19.dupl_rm.bam OUTPUT=FL.19.bam RGID=FL.19 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FL.19;

rm -rf temp.FL.19
rm FL.19.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FL.19.bam
/home/knam/save/programs/samtools-1.9/samtools stats FL.19.bam > FL.19.stats
