#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/FG3.filtered.paired.1.fq.gz -2 /home/knam/save/fq/FG3.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/FG3.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o FG3.sorted.bam FG3.raw.bam

#rm FG3.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.FG3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FG3.sorted.bam OUTPUT=FG3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FG3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.FG3
#rm FG3.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.FG3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FG3.dupl_rm.bam OUTPUT=FG3.bam RGID=FG3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FG3;

#rm -rf temp.FG3
#rm FG3.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index FG3.bam
#/home/knam/save/programs/samtools-1.9/samtools stats FG3.bam > FG3.stats
