#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/PR15.filtered.paired.1.fq.gz -2 /home/knam/save/fq/PR15.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/PR15.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o PR15.sorted.bam PR15.raw.bam

#rm PR15.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR15 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR15.sorted.bam OUTPUT=PR15.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR15.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.PR15
#rm PR15.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR15 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR15.dupl_rm.bam OUTPUT=PR15.bam RGID=PR15 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR15;

#rm -rf temp.PR15
#rm PR15.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index PR15.bam
#/home/knam/save/programs/samtools-1.9/samtools stats PR15.bam > PR15.stats
