#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/PR27.filtered.paired.1.fq.gz -2 /home/knam/save/fq/PR27.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/PR27.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o PR27.sorted.bam PR27.raw.bam

#rm PR27.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR27 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR27.sorted.bam OUTPUT=PR27.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR27.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.PR27
#rm PR27.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR27 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR27.dupl_rm.bam OUTPUT=PR27.bam RGID=PR27 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR27;

#rm -rf temp.PR27
#rm PR27.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index PR27.bam
#/home/knam/save/programs/samtools-1.9/samtools stats PR27.bam > PR27.stats
