#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/PR30.filtered.paired.1.fq.gz -2 /home/knam/save/fq/PR30.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/PR30.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o PR30.sorted.bam PR30.raw.bam

#rm PR30.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR30 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR30.sorted.bam OUTPUT=PR30.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR30.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.PR30
#rm PR30.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR30 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR30.dupl_rm.bam OUTPUT=PR30.bam RGID=PR30 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR30;

#rm -rf temp.PR30
#rm PR30.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index PR30.bam
#/home/knam/save/programs/samtools-1.9/samtools stats PR30.bam > PR30.stats
