#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/PR33.filtered.paired.1.fq.gz -2 /home/knam/save/fq/PR33.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/PR33.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o PR33.sorted.bam PR33.raw.bam

#rm PR33.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR33 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=PR33.sorted.bam OUTPUT=PR33.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=PR33.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.PR33
#rm PR33.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.PR33 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=PR33.dupl_rm.bam OUTPUT=PR33.bam RGID=PR33 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=PR33;

#rm -rf temp.PR33
#rm PR33.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index PR33.bam
#/home/knam/save/programs/samtools-1.9/samtools stats PR33.bam > PR33.stats
