#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/FL.16.filtered.paired.1.fq.gz -2 /home/knam/save/fq/FL.16.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/FL.16.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o FL.16.sorted.bam FL.16.raw.bam

#rm FL.16.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.FL.16 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FL.16.sorted.bam OUTPUT=FL.16.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FL.16.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.FL.16
#rm FL.16.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.FL.16 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FL.16.dupl_rm.bam OUTPUT=FL.16.bam RGID=FL.16 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FL.16;

#rm -rf temp.FL.16
#rm FL.16.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index FL.16.bam
#/home/knam/save/programs/samtools-1.9/samtools stats FL.16.bam > FL.16.stats
