#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/FL.18.filtered.paired.1.fq.gz -2 /home/knam/save/fq/FL.18.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/FL.18.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o FL.18.sorted.bam FL.18.raw.bam

#rm FL.18.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.FL.18 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FL.18.sorted.bam OUTPUT=FL.18.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FL.18.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.FL.18
#rm FL.18.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.FL.18 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FL.18.dupl_rm.bam OUTPUT=FL.18.bam RGID=FL.18 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FL.18;

#rm -rf temp.FL.18
#rm FL.18.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index FL.18.bam
#/home/knam/save/programs/samtools-1.9/samtools stats FL.18.bam > FL.18.stats
