#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/FL.20.filtered.paired.1.fq.gz -2 /home/knam/save/fq/FL.20.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/FL.20.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o FL.20.sorted.bam FL.20.raw.bam

#rm FL.20.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.FL.20 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FL.20.sorted.bam OUTPUT=FL.20.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FL.20.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.FL.20
#rm FL.20.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.FL.20 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FL.20.dupl_rm.bam OUTPUT=FL.20.bam RGID=FL.20 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FL.20;

#rm -rf temp.FL.20
#rm FL.20.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index FL.20.bam
#/home/knam/save/programs/samtools-1.9/samtools stats FL.20.bam > FL.20.stats
