#!/bin/bash

#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/save/fq/G_1.2.filtered.paired.1.fq.gz -2 /home/knam/save/fq/G_1.2.filtered.paired.2.fq.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.2/G_1.2.raw.bam

cd ../bam.2

/home/knam/save/programs/samtools-1.9/samtools sort -o G_1.2.sorted.bam G_1.2.raw.bam

#rm G_1.2.raw.bam

java -Xmx10g -Djava.io.tmpdir=temp.G_1.2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=G_1.2.sorted.bam OUTPUT=G_1.2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=G_1.2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

#rm -rf temp.G_1.2
#rm G_1.2.sorted.bam

java -Xmx10g -Djava.io.tmpdir=temp.G_1.2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=G_1.2.dupl_rm.bam OUTPUT=G_1.2.bam RGID=G_1.2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=G_1.2;

#rm -rf temp.G_1.2
#rm G_1.2.dupl_rm.bam

#/home/knam/save/programs/samtools-1.9/samtools index G_1.2.bam
#/home/knam/save/programs/samtools-1.9/samtools stats G_1.2.bam > G_1.2.stats
