#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/353m.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/353m.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/353m.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o 353m.sorted.bam 353m.raw.bam

rm 353m.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.353m -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=353m.sorted.bam OUTPUT=353m.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=353m.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.353m
rm 353m.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.353m -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=353m.dupl_rm.bam OUTPUT=353m.bam RGID=353m RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=353m;

rm -rf temp.353m
rm 353m.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 353m.bam
/home/knam/save/programs/samtools-1.9/samtools stats 353m.bam > 353m.stats
