#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/56F.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/56F.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/56F.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o 56F.sorted.bam 56F.raw.bam

rm 56F.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.56F -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=56F.sorted.bam OUTPUT=56F.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=56F.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.56F
rm 56F.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.56F -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=56F.dupl_rm.bam OUTPUT=56F.bam RGID=56F RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=56F;

rm -rf temp.56F
rm 56F.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 56F.bam
/home/knam/save/programs/samtools-1.9/samtools stats 56F.bam > 56F.stats
