#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/CC40.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/CC40.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/CC40.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o CC40.sorted.bam CC40.raw.bam

rm CC40.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.CC40 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=CC40.sorted.bam OUTPUT=CC40.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=CC40.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.CC40
rm CC40.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.CC40 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=CC40.dupl_rm.bam OUTPUT=CC40.bam RGID=CC40 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=CC40;

rm -rf temp.CC40
rm CC40.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index CC40.bam
/home/knam/save/programs/samtools-1.9/samtools stats CC40.bam > CC40.stats
