#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/293m.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/293m.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/293m.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o 293m.sorted.bam 293m.raw.bam

rm 293m.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.293m -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=293m.sorted.bam OUTPUT=293m.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=293m.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.293m
rm 293m.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.293m -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=293m.dupl_rm.bam OUTPUT=293m.bam RGID=293m RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=293m;

rm -rf temp.293m
rm 293m.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 293m.bam
/home/knam/save/programs/samtools-1.9/samtools stats 293m.bam > 293m.stats
