#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/CC96.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/CC96.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/CC96.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o CC96.sorted.bam CC96.raw.bam

rm CC96.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.CC96 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=CC96.sorted.bam OUTPUT=CC96.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=CC96.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.CC96
rm CC96.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.CC96 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=CC96.dupl_rm.bam OUTPUT=CC96.bam RGID=CC96 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=CC96;

rm -rf temp.CC96
rm CC96.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index CC96.bam
/home/knam/save/programs/samtools-1.9/samtools stats CC96.bam > CC96.stats
