#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/KAB.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/KAB.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/KAB.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o KAB.sorted.bam KAB.raw.bam

rm KAB.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KAB -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KAB.sorted.bam OUTPUT=KAB.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KAB.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KAB
rm KAB.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KAB -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KAB.dupl_rm.bam OUTPUT=KAB.bam RGID=KAB RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KAB;

rm -rf temp.KAB
rm KAB.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KAB.bam
/home/knam/save/programs/samtools-1.9/samtools stats KAB.bam > KAB.stats
