#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal17.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal17.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/Mal17.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal17.sorted.bam Mal17.raw.bam

rm Mal17.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal17 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal17.sorted.bam OUTPUT=Mal17.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal17.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal17
rm Mal17.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal17 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal17.dupl_rm.bam OUTPUT=Mal17.bam RGID=Mal17 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal17;

rm -rf temp.Mal17
rm Mal17.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal17.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal17.bam > Mal17.stats
