#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal3sb.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal3sb.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/Mal3sb.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal3sb.sorted.bam Mal3sb.raw.bam

rm Mal3sb.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal3sb -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal3sb.sorted.bam OUTPUT=Mal3sb.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal3sb.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal3sb
rm Mal3sb.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal3sb -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal3sb.dupl_rm.bam OUTPUT=Mal3sb.bam RGID=Mal3sb RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal3sb;

rm -rf temp.Mal3sb
rm Mal3sb.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal3sb.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal3sb.bam > Mal3sb.stats
