#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal41.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal41.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/Mal41.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal41.sorted.bam Mal41.raw.bam

rm Mal41.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal41 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal41.sorted.bam OUTPUT=Mal41.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal41.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal41
rm Mal41.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal41 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal41.dupl_rm.bam OUTPUT=Mal41.bam RGID=Mal41 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal41;

rm -rf temp.Mal41
rm Mal41.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal41.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal41.bam > Mal41.stats
