#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal51.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal51.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/Mal51.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal51.sorted.bam Mal51.raw.bam

rm Mal51.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal51 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal51.sorted.bam OUTPUT=Mal51.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal51.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal51
rm Mal51.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal51 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal51.dupl_rm.bam OUTPUT=Mal51.bam RGID=Mal51 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal51;

rm -rf temp.Mal51
rm Mal51.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal51.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal51.bam > Mal51.stats
