#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal52.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal52.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/Mal52.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal52.sorted.bam Mal52.raw.bam

rm Mal52.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal52 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal52.sorted.bam OUTPUT=Mal52.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal52.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal52
rm Mal52.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal52 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal52.dupl_rm.bam OUTPUT=Mal52.bam RGID=Mal52 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal52;

rm -rf temp.Mal52
rm Mal52.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal52.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal52.bam > Mal52.stats
