#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal7.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal7.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/Mal7.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal7.sorted.bam Mal7.raw.bam

rm Mal7.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal7 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal7.sorted.bam OUTPUT=Mal7.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal7.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal7
rm Mal7.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal7 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal7.dupl_rm.bam OUTPUT=Mal7.bam RGID=Mal7 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal7;

rm -rf temp.Mal7
rm Mal7.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal7.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal7.bam > Mal7.stats
