#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/MIX5.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/MIX5.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/MIX5.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o MIX5.sorted.bam MIX5.raw.bam

rm MIX5.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.MIX5 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=MIX5.sorted.bam OUTPUT=MIX5.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=MIX5.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.MIX5
rm MIX5.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.MIX5 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=MIX5.dupl_rm.bam OUTPUT=MIX5.bam RGID=MIX5 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=MIX5;

rm -rf temp.MIX5
rm MIX5.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index MIX5.bam
/home/knam/save/programs/samtools-1.9/samtools stats MIX5.bam > MIX5.stats
