#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/336K.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/336K.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/336K.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o 336K.sorted.bam 336K.raw.bam

rm 336K.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.336K -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=336K.sorted.bam OUTPUT=336K.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=336K.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.336K
rm 336K.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.336K -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=336K.dupl_rm.bam OUTPUT=336K.bam RGID=336K RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=336K;

rm -rf temp.336K
rm 336K.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 336K.bam
/home/knam/save/programs/samtools-1.9/samtools stats 336K.bam > 336K.stats
