#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/NGO.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/NGO.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/NGO.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o NGO.sorted.bam NGO.raw.bam

rm NGO.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.NGO -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=NGO.sorted.bam OUTPUT=NGO.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=NGO.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.NGO
rm NGO.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.NGO -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=NGO.dupl_rm.bam OUTPUT=NGO.bam RGID=NGO RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=NGO;

rm -rf temp.NGO
rm NGO.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index NGO.bam
/home/knam/save/programs/samtools-1.9/samtools stats NGO.bam > NGO.stats
