#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/340k.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/340k.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o /home/knam/work/sfrugiperda_SNP/nuc_3/bam/340k.raw.bam

cd /home/knam/work/sfrugiperda_SNP/nuc_3/bam

/home/knam/save/programs/samtools-1.9/samtools sort -o 340k.sorted.bam 340k.raw.bam

rm 340k.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.340k -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=340k.sorted.bam OUTPUT=340k.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=340k.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.340k
rm 340k.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.340k -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=340k.dupl_rm.bam OUTPUT=340k.bam RGID=340k RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=340k;

rm -rf temp.340k
rm 340k.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 340k.bam
/home/knam/save/programs/samtools-1.9/samtools stats 340k.bam > 340k.stats
