#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=20G
#SBATCH -p unlimitq

cd /home/knam/work/sfrugiperda_SNP/mt/gvcf.1

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/mt/ref/sfmt.ref.smrt.fa -I ../bam.1/F1a.bam -O F1a.g.vcf.gz -ERC GVCF
#/home/knam/save/programs/htslib-1.9/bgzip -f F1a.g.vcf
