#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/BRG1.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/BRG1.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/BRG1.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o BRG1.sorted.bam BRG1.raw.bam

rm BRG1.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.BRG1 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=BRG1.sorted.bam OUTPUT=BRG1.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=BRG1.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.BRG1
rm BRG1.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.BRG1 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=BRG1.dupl_rm.bam OUTPUT=BRG1.bam RGID=BRG1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=BRG1;

rm -rf temp.BRG1
rm BRG1.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index BRG1.bam
/home/knam/save/programs/samtools-1.9/samtools stats BRG1.bam > BRG1.stats
