#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/BRG2.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/BRG2.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/BRG2.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o BRG2.sorted.bam BRG2.raw.bam

rm BRG2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.BRG2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=BRG2.sorted.bam OUTPUT=BRG2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=BRG2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.BRG2
rm BRG2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.BRG2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=BRG2.dupl_rm.bam OUTPUT=BRG2.bam RGID=BRG2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=BRG2;

rm -rf temp.BRG2
rm BRG2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index BRG2.bam
/home/knam/save/programs/samtools-1.9/samtools stats BRG2.bam > BRG2.stats
