#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/BRG3.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/BRG3.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/BRG3.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o BRG3.sorted.bam BRG3.raw.bam

rm BRG3.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.BRG3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=BRG3.sorted.bam OUTPUT=BRG3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=BRG3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.BRG3
rm BRG3.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.BRG3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=BRG3.dupl_rm.bam OUTPUT=BRG3.bam RGID=BRG3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=BRG3;

rm -rf temp.BRG3
rm BRG3.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index BRG3.bam
/home/knam/save/programs/samtools-1.9/samtools stats BRG3.bam > BRG3.stats
