#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/FCC2.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC2.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/FCC2.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC2.sorted.bam FCC2.raw.bam

rm FCC2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC2.sorted.bam OUTPUT=FCC2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC2
rm FCC2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC2.dupl_rm.bam OUTPUT=FCC2.bam RGID=FCC2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC2;

rm -rf temp.FCC2
rm FCC2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC2.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC2.bam > FCC2.stats
