#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ12.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ12.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/FGJ12.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ12.sorted.bam FGJ12.raw.bam

rm FGJ12.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ12 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ12.sorted.bam OUTPUT=FGJ12.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ12.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ12
rm FGJ12.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ12 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ12.dupl_rm.bam OUTPUT=FGJ12.bam RGID=FGJ12 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ12;

rm -rf temp.FGJ12
rm FGJ12.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ12.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ12.bam > FGJ12.stats
