#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ2.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ2.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/FGJ2.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ2.sorted.bam FGJ2.raw.bam

rm FGJ2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ2.sorted.bam OUTPUT=FGJ2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ2
rm FGJ2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ2.dupl_rm.bam OUTPUT=FGJ2.bam RGID=FGJ2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ2;

rm -rf temp.FGJ2
rm FGJ2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ2.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ2.bam > FGJ2.stats
