#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/B2.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B2.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/B2.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o B2.sorted.bam B2.raw.bam

rm B2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B2.sorted.bam OUTPUT=B2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B2
rm B2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B2.dupl_rm.bam OUTPUT=B2.bam RGID=B2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B2;

rm -rf temp.B2
rm B2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B2.bam
/home/knam/save/programs/samtools-1.9/samtools stats B2.bam > B2.stats
