#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ4.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ4.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/FGJ4.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ4.sorted.bam FGJ4.raw.bam

rm FGJ4.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ4 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ4.sorted.bam OUTPUT=FGJ4.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ4.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ4
rm FGJ4.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ4 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ4.dupl_rm.bam OUTPUT=FGJ4.bam RGID=FGJ4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ4;

rm -rf temp.FGJ4
rm FGJ4.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ4.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ4.bam > FGJ4.stats
