#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ8.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ8.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/FGJ8.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ8.sorted.bam FGJ8.raw.bam

rm FGJ8.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ8 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ8.sorted.bam OUTPUT=FGJ8.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ8.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ8
rm FGJ8.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ8 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ8.dupl_rm.bam OUTPUT=FGJ8.bam RGID=FGJ8 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ8;

rm -rf temp.FGJ8
rm FGJ8.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ8.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ8.bam > FGJ8.stats
