#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ9.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ9.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/FGJ9.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ9.sorted.bam FGJ9.raw.bam

rm FGJ9.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ9 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ9.sorted.bam OUTPUT=FGJ9.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ9.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ9
rm FGJ9.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ9 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ9.dupl_rm.bam OUTPUT=FGJ9.bam RGID=FGJ9 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ9;

rm -rf temp.FGJ9
rm FGJ9.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ9.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ9.bam > FGJ9.stats
