#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0036.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0036.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/KNAM_0036.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o KNAM_0036.sorted.bam KNAM_0036.raw.bam

rm KNAM_0036.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0036 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KNAM_0036.sorted.bam OUTPUT=KNAM_0036.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KNAM_0036.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KNAM_0036
rm KNAM_0036.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0036 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KNAM_0036.dupl_rm.bam OUTPUT=KNAM_0036.bam RGID=KNAM_0036 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KNAM_0036;

rm -rf temp.KNAM_0036
rm KNAM_0036.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KNAM_0036.bam
/home/knam/save/programs/samtools-1.9/samtools stats KNAM_0036.bam > KNAM_0036.stats
