#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/B4.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B4.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/B4.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o B4.sorted.bam B4.raw.bam

rm B4.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B4 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B4.sorted.bam OUTPUT=B4.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B4.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B4
rm B4.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B4 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B4.dupl_rm.bam OUTPUT=B4.bam RGID=B4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B4;

rm -rf temp.B4
rm B4.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B4.bam
/home/knam/save/programs/samtools-1.9/samtools stats B4.bam > B4.stats
