#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0045.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0045.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/KNAM_0045.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o KNAM_0045.sorted.bam KNAM_0045.raw.bam

rm KNAM_0045.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0045 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KNAM_0045.sorted.bam OUTPUT=KNAM_0045.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KNAM_0045.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KNAM_0045
rm KNAM_0045.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0045 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KNAM_0045.dupl_rm.bam OUTPUT=KNAM_0045.bam RGID=KNAM_0045 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KNAM_0045;

rm -rf temp.KNAM_0045
rm KNAM_0045.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KNAM_0045.bam
/home/knam/save/programs/samtools-1.9/samtools stats KNAM_0045.bam > KNAM_0045.stats
