#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/MS_R_R2.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/MS_R_R2.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/MS_R_R2.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o MS_R_R2.sorted.bam MS_R_R2.raw.bam

rm MS_R_R2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.MS_R_R2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=MS_R_R2.sorted.bam OUTPUT=MS_R_R2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=MS_R_R2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.MS_R_R2
rm MS_R_R2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.MS_R_R2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=MS_R_R2.dupl_rm.bam OUTPUT=MS_R_R2.bam RGID=MS_R_R2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=MS_R_R2;

rm -rf temp.MS_R_R2
rm MS_R_R2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index MS_R_R2.bam
/home/knam/save/programs/samtools-1.9/samtools stats MS_R_R2.bam > MS_R_R2.stats
