#!/bin/bash

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/sfrugiperda_SNP/fq/S3.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/S3.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.1/S3.raw.bam

cd ../bam.1

/home/knam/save/programs/samtools-1.9/samtools sort -o S3.sorted.bam S3.raw.bam

rm S3.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.S3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=S3.sorted.bam OUTPUT=S3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=S3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.S3
rm S3.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.S3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=S3.dupl_rm.bam OUTPUT=S3.bam RGID=S3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=S3;

rm -rf temp.S3
rm S3.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index S3.bam
/home/knam/save/programs/samtools-1.9/samtools stats S3.bam > S3.stats
