#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=20G
#SBATCH -p unlimitq


cd /home/knam/work/sfrugiperda_SNP/mt/gvcf.2

/home/knam/save/programs/samtools-1.9/samtools index ../bam.2/G_2.3.bam

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/mt/ref/sfmt.ref.smrt.fa -I ../bam.2/G_2.3.bam -O G_2.3.g.vcf.gz -ERC GVCF
#/home/knam/save/programs/htslib-1.9/bgzip -f G_2.3.g.vcf
