#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=40G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/gvcf

/home/knam/save/programs/samtools-1.9/samtools index ../bam/FG3.bam

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/nuc_2/ref/sfC.ver7.fa -I ../bam/FG3.bam -O FG3.g.vcf.gz -ERC GVCF
