#!/bin/bash
#SBATCH -p unlimitq
#SBATCH -c 4
#SBATCH --mem=40G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/gvcf

/home/knam/save/programs/samtools-1.9/samtools index ../bam/PR32.bam

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/nuc_2/ref/sfC.ver7.fa -I ../bam/PR32.bam -O PR32.g.vcf.gz -ERC GVCF
