#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=40G

cd /home/knam/work/sfrugiperda_SNP/nuc_2/gvcf

/home/knam/save/programs/samtools-1.9/samtools index ../bam/G_1.2.bam

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/nuc_2/ref/sfC.ver7.fa -I ../bam/G_1.2.bam -O G_1.2.g.vcf.gz -ERC GVCF
