#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B9.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B9.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B9.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B9.sorted.bam B9.raw.bam

rm B9.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B9 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B9.sorted.bam OUTPUT=B9.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B9.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B9
rm B9.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B9 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B9.dupl_rm.bam OUTPUT=B9.bam RGID=B9 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B9;

rm -rf temp.B9
rm B9.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B9.bam
/home/knam/save/programs/samtools-1.9/samtools stats B9.bam > B9.stats
