#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B1.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B1.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B1.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B1.sorted.bam B1.raw.bam

rm B1.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B1 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B1.sorted.bam OUTPUT=B1.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B1.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B1
rm B1.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B1 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B1.dupl_rm.bam OUTPUT=B1.bam RGID=B1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B1;

rm -rf temp.B1
rm B1.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B1.bam
/home/knam/save/programs/samtools-1.9/samtools stats B1.bam > B1.stats
