#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/BCW2.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/BCW2.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/BCW2.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o BCW2.sorted.bam BCW2.raw.bam

rm BCW2.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.BCW2 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=BCW2.sorted.bam OUTPUT=BCW2.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=BCW2.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.BCW2
rm BCW2.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.BCW2 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=BCW2.dupl_rm.bam OUTPUT=BCW2.bam RGID=BCW2 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=BCW2;

rm -rf temp.BCW2
rm BCW2.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index BCW2.bam
/home/knam/save/programs/samtools-1.9/samtools stats BCW2.bam > BCW2.stats
