#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0047.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0047.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/KNAM_0047.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o KNAM_0047.sorted.bam KNAM_0047.raw.bam

rm KNAM_0047.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0047 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KNAM_0047.sorted.bam OUTPUT=KNAM_0047.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KNAM_0047.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KNAM_0047
rm KNAM_0047.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0047 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KNAM_0047.dupl_rm.bam OUTPUT=KNAM_0047.bam RGID=KNAM_0047 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KNAM_0047;

rm -rf temp.KNAM_0047
rm KNAM_0047.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KNAM_0047.bam
/home/knam/save/programs/samtools-1.9/samtools stats KNAM_0047.bam > KNAM_0047.stats
