#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ6.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ6.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FGJ6.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ6.sorted.bam FGJ6.raw.bam

rm FGJ6.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ6 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ6.sorted.bam OUTPUT=FGJ6.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ6.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ6
rm FGJ6.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ6 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ6.dupl_rm.bam OUTPUT=FGJ6.bam RGID=FGJ6 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ6;

rm -rf temp.FGJ6
rm FGJ6.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ6.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ6.bam > FGJ6.stats
