#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ3.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ3.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FGJ3.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ3.sorted.bam FGJ3.raw.bam

rm FGJ3.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ3.sorted.bam OUTPUT=FGJ3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ3
rm FGJ3.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ3.dupl_rm.bam OUTPUT=FGJ3.bam RGID=FGJ3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ3;

rm -rf temp.FGJ3
rm FGJ3.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ3.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ3.bam > FGJ3.stats
