#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/M1a.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/M1a.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/M1a.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o M1a.sorted.bam M1a.raw.bam

rm M1a.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.M1a -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=M1a.sorted.bam OUTPUT=M1a.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=M1a.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.M1a
rm M1a.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.M1a -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=M1a.dupl_rm.bam OUTPUT=M1a.bam RGID=M1a RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=M1a;

rm -rf temp.M1a
rm M1a.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index M1a.bam
/home/knam/save/programs/samtools-1.9/samtools stats M1a.bam > M1a.stats
