#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ10.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ10.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FGJ10.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ10.sorted.bam FGJ10.raw.bam

rm FGJ10.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ10 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ10.sorted.bam OUTPUT=FGJ10.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ10.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ10
rm FGJ10.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ10 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ10.dupl_rm.bam OUTPUT=FGJ10.bam RGID=FGJ10 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ10;

rm -rf temp.FGJ10
rm FGJ10.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ10.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ10.bam > FGJ10.stats
