#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/F1a.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/F1a.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/F1a.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o F1a.sorted.bam F1a.raw.bam

rm F1a.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.F1a -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=F1a.sorted.bam OUTPUT=F1a.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=F1a.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.F1a
rm F1a.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.F1a -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=F1a.dupl_rm.bam OUTPUT=F1a.bam RGID=F1a RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=F1a;

rm -rf temp.F1a
rm F1a.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index F1a.bam
/home/knam/save/programs/samtools-1.9/samtools stats F1a.bam > F1a.stats
