#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B6.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B6.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B6.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B6.sorted.bam B6.raw.bam

rm B6.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B6 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B6.sorted.bam OUTPUT=B6.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B6.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B6
rm B6.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B6 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B6.dupl_rm.bam OUTPUT=B6.bam RGID=B6 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B6;

rm -rf temp.B6
rm B6.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B6.bam
/home/knam/save/programs/samtools-1.9/samtools stats B6.bam > B6.stats
