#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FCC1.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC1.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FCC1.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC1.sorted.bam FCC1.raw.bam

rm FCC1.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC1 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC1.sorted.bam OUTPUT=FCC1.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC1.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC1
rm FCC1.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC1 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC1.dupl_rm.bam OUTPUT=FCC1.bam RGID=FCC1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC1;

rm -rf temp.FCC1
rm FCC1.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC1.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC1.bam > FCC1.stats
