#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/MS_C_C6.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/MS_C_C6.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/MS_C_C6.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o MS_C_C6.sorted.bam MS_C_C6.raw.bam

rm MS_C_C6.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.MS_C_C6 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=MS_C_C6.sorted.bam OUTPUT=MS_C_C6.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=MS_C_C6.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.MS_C_C6
rm MS_C_C6.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.MS_C_C6 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=MS_C_C6.dupl_rm.bam OUTPUT=MS_C_C6.bam RGID=MS_C_C6 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=MS_C_C6;

rm -rf temp.MS_C_C6
rm MS_C_C6.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index MS_C_C6.bam
/home/knam/save/programs/samtools-1.9/samtools stats MS_C_C6.bam > MS_C_C6.stats
