#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/MS_R_R7.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/MS_R_R7.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/MS_R_R7.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o MS_R_R7.sorted.bam MS_R_R7.raw.bam

rm MS_R_R7.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.MS_R_R7 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=MS_R_R7.sorted.bam OUTPUT=MS_R_R7.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=MS_R_R7.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.MS_R_R7
rm MS_R_R7.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.MS_R_R7 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=MS_R_R7.dupl_rm.bam OUTPUT=MS_R_R7.bam RGID=MS_R_R7 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=MS_R_R7;

rm -rf temp.MS_R_R7
rm MS_R_R7.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index MS_R_R7.bam
/home/knam/save/programs/samtools-1.9/samtools stats MS_R_R7.bam > MS_R_R7.stats
