#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FCC3.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC3.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FCC3.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC3.sorted.bam FCC3.raw.bam

rm FCC3.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC3.sorted.bam OUTPUT=FCC3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC3
rm FCC3.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC3.dupl_rm.bam OUTPUT=FCC3.bam RGID=FCC3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC3;

rm -rf temp.FCC3
rm FCC3.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC3.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC3.bam > FCC3.stats
