#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 --very-sensitive-local -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FCC5.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC5.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FCC5.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC5.sorted.bam FCC5.raw.bam

rm FCC5.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC5 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC5.sorted.bam OUTPUT=FCC5.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC5.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC5
rm FCC5.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC5 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC5.dupl_rm.bam OUTPUT=FCC5.bam RGID=FCC5 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC5;

rm -rf temp.FCC5
rm FCC5.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC5.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC5.bam > FCC5.stats
