#!/bin/bash
#SBATCH --mem=50G  #Memory we need to run this script

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref  # place of the reference genome

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B10.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B10.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B10.raw.bam # using bowtie2 for mapping. sfC. ver7 --> Version of reference we use. We need fastq files(.gz) to generate raw bam files (with bowtie2)

cd ../bam # Check if raw bam files is generate

/home/knam/save/programs/samtools-1.9/samtools sort -o B10.sorted.bam B10.raw.bam  # sorting bam files (with samtools)

rm B10.raw.bam  #remove raw bam files

java -Xmx4g -Djava.io.tmpdir=temp.B10 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B10.sorted.bam OUTPUT=B10.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B10.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 #PCR make error,so we need remove PCR duplicates from bam files with picard.jar software

rm -rf temp.B10
rm B10.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B10 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B10.dupl_rm.bam OUTPUT=B10.bam RGID=B10 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B10; # Add names for each sample bam files (with picard.jar) 

rm -rf temp.B10
rm B10.dupl_rm.bam  #remove file of duplicate (PCR)

/home/knam/save/programs/samtools-1.9/samtools index B10.bam #Indexing bam files(with samtools)
/home/knam/save/programs/samtools-1.9/samtools stats B10.bam > B10.stats  # Statistic (with samtools)
