#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ5.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ5.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FGJ5.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ5.sorted.bam FGJ5.raw.bam

rm FGJ5.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ5 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ5.sorted.bam OUTPUT=FGJ5.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ5.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ5
rm FGJ5.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ5 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ5.dupl_rm.bam OUTPUT=FGJ5.bam RGID=FGJ5 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ5;

rm -rf temp.FGJ5
rm FGJ5.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ5.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ5.bam > FGJ5.stats
