#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FCC4.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC4.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FCC4.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC4.sorted.bam FCC4.raw.bam

rm FCC4.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC4 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC4.sorted.bam OUTPUT=FCC4.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC4.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC4
rm FCC4.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC4 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC4.dupl_rm.bam OUTPUT=FCC4.bam RGID=FCC4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC4;

rm -rf temp.FCC4
rm FCC4.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC4.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC4.bam > FCC4.stats
