#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FCC7.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC7.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FCC7.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC7.sorted.bam FCC7.raw.bam

rm FCC7.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC7 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC7.sorted.bam OUTPUT=FCC7.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC7.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC7
rm FCC7.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC7 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC7.dupl_rm.bam OUTPUT=FCC7.bam RGID=FCC7 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC7;

rm -rf temp.FCC7
rm FCC7.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC7.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC7.bam > FCC7.stats
