#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B3.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B3.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B3.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B3.sorted.bam B3.raw.bam

rm B3.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B3 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B3.sorted.bam OUTPUT=B3.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B3.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B3
rm B3.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B3 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B3.dupl_rm.bam OUTPUT=B3.bam RGID=B3 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B3;

rm -rf temp.B3
rm B3.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B3.bam
/home/knam/save/programs/samtools-1.9/samtools stats B3.bam > B3.stats
