#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FCC8.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FCC8.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FCC8.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FCC8.sorted.bam FCC8.raw.bam

rm FCC8.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC8 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FCC8.sorted.bam OUTPUT=FCC8.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FCC8.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FCC8
rm FCC8.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FCC8 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FCC8.dupl_rm.bam OUTPUT=FCC8.bam RGID=FCC8 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FCC8;

rm -rf temp.FCC8
rm FCC8.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FCC8.bam
/home/knam/save/programs/samtools-1.9/samtools stats FCC8.bam > FCC8.stats
