#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ7.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ7.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FGJ7.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ7.sorted.bam FGJ7.raw.bam

rm FGJ7.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ7 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ7.sorted.bam OUTPUT=FGJ7.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ7.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ7
rm FGJ7.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ7 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ7.dupl_rm.bam OUTPUT=FGJ7.bam RGID=FGJ7 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ7;

rm -rf temp.FGJ7
rm FGJ7.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ7.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ7.bam > FGJ7.stats
