#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B5.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B5.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B5.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B5.sorted.bam B5.raw.bam

rm B5.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B5 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B5.sorted.bam OUTPUT=B5.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B5.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B5
rm B5.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B5 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B5.dupl_rm.bam OUTPUT=B5.bam RGID=B5 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B5;

rm -rf temp.B5
rm B5.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B5.bam
/home/knam/save/programs/samtools-1.9/samtools stats B5.bam > B5.stats
