#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/FGJ11.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/FGJ11.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/FGJ11.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o FGJ11.sorted.bam FGJ11.raw.bam

rm FGJ11.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ11 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=FGJ11.sorted.bam OUTPUT=FGJ11.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=FGJ11.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.FGJ11
rm FGJ11.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.FGJ11 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=FGJ11.dupl_rm.bam OUTPUT=FGJ11.bam RGID=FGJ11 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=FGJ11;

rm -rf temp.FGJ11
rm FGJ11.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index FGJ11.bam
/home/knam/save/programs/samtools-1.9/samtools stats FGJ11.bam > FGJ11.stats
