#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0042.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/KNAM_0042.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/KNAM_0042.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o KNAM_0042.sorted.bam KNAM_0042.raw.bam

rm KNAM_0042.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0042 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KNAM_0042.sorted.bam OUTPUT=KNAM_0042.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KNAM_0042.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KNAM_0042
rm KNAM_0042.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KNAM_0042 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KNAM_0042.dupl_rm.bam OUTPUT=KNAM_0042.bam RGID=KNAM_0042 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KNAM_0042;

rm -rf temp.KNAM_0042
rm KNAM_0042.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KNAM_0042.bam
/home/knam/save/programs/samtools-1.9/samtools stats KNAM_0042.bam > KNAM_0042.stats
