#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B7.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B7.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B7.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B7.sorted.bam B7.raw.bam

rm B7.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B7 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B7.sorted.bam OUTPUT=B7.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B7.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B7
rm B7.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B7 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B7.dupl_rm.bam OUTPUT=B7.bam RGID=B7 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B7;

rm -rf temp.B7
rm B7.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B7.bam
/home/knam/save/programs/samtools-1.9/samtools stats B7.bam > B7.stats
