#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B8.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B8.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B8.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B8.sorted.bam B8.raw.bam

rm B8.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B8 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B8.sorted.bam OUTPUT=B8.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B8.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B8
rm B8.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B8 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B8.dupl_rm.bam OUTPUT=B8.bam RGID=B8 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B8;

rm -rf temp.B8
rm B8.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B8.bam
/home/knam/save/programs/samtools-1.9/samtools stats B8.bam > B8.stats
