#!/bin/bash
#SBATCH --mem=50G

cd /home/knam/work/sfrugiperda_SNP/nuc_1/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfC.ver7 -1 /home/knam/work/sfrugiperda_SNP/fq/B12.pair1.truncated.gz -2 /home/knam/work/sfrugiperda_SNP/fq/B12.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -b -h -o ../bam/B12.raw.bam

cd ../bam

/home/knam/save/programs/samtools-1.9/samtools sort -o B12.sorted.bam B12.raw.bam

rm B12.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.B12 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=B12.sorted.bam OUTPUT=B12.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=B12.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.B12
rm B12.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.B12 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=B12.dupl_rm.bam OUTPUT=B12.bam RGID=B12 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=B12;

rm -rf temp.B12
rm B12.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index B12.bam
/home/knam/save/programs/samtools-1.9/samtools stats B12.bam > B12.stats
