#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/142m.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/142m.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/142m.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o 142m.sorted.bam 142m.raw.bam

rm 142m.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.142m -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=142m.sorted.bam OUTPUT=142m.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=142m.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.142m
rm 142m.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.142m -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=142m.dupl_rm.bam OUTPUT=142m.bam RGID=142m RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=142m;

rm -rf temp.142m
rm 142m.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 142m.bam
/home/knam/save/programs/samtools-1.9/samtools stats 142m.bam > 142m.stats
