#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/174F.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/174F.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/174F.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o 174F.sorted.bam 174F.raw.bam

rm 174F.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.174F -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=174F.sorted.bam OUTPUT=174F.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=174F.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.174F
rm 174F.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.174F -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=174F.dupl_rm.bam OUTPUT=174F.bam RGID=174F RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=174F;

rm -rf temp.174F
rm 174F.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 174F.bam
/home/knam/save/programs/samtools-1.9/samtools stats 174F.bam > 174F.stats
