#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/C1.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/C1.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/C1.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o C1.sorted.bam C1.raw.bam

rm C1.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.C1 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=C1.sorted.bam OUTPUT=C1.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=C1.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.C1
rm C1.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.C1 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=C1.dupl_rm.bam OUTPUT=C1.bam RGID=C1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=C1;

rm -rf temp.C1
rm C1.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index C1.bam
/home/knam/save/programs/samtools-1.9/samtools stats C1.bam > C1.stats
