#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/CC66.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/CC66.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/CC66.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o CC66.sorted.bam CC66.raw.bam

rm CC66.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.CC66 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=CC66.sorted.bam OUTPUT=CC66.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=CC66.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.CC66
rm CC66.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.CC66 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=CC66.dupl_rm.bam OUTPUT=CC66.bam RGID=CC66 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=CC66;

rm -rf temp.CC66
rm CC66.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index CC66.bam
/home/knam/save/programs/samtools-1.9/samtools stats CC66.bam > CC66.stats
