#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/KAT.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/KAT.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/KAT.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o KAT.sorted.bam KAT.raw.bam

rm KAT.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KAT -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KAT.sorted.bam OUTPUT=KAT.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KAT.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KAT
rm KAT.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KAT -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KAT.dupl_rm.bam OUTPUT=KAT.bam RGID=KAT RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KAT;

rm -rf temp.KAT
rm KAT.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KAT.bam
/home/knam/save/programs/samtools-1.9/samtools stats KAT.bam > KAT.stats
