#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/KUM.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/KUM.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/KUM.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o KUM.sorted.bam KUM.raw.bam

rm KUM.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.KUM -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=KUM.sorted.bam OUTPUT=KUM.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=KUM.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.KUM
rm KUM.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.KUM -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=KUM.dupl_rm.bam OUTPUT=KUM.bam RGID=KUM RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=KUM;

rm -rf temp.KUM
rm KUM.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index KUM.bam
/home/knam/save/programs/samtools-1.9/samtools stats KUM.bam > KUM.stats
