#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal12.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal12.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/Mal12.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal12.sorted.bam Mal12.raw.bam

rm Mal12.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal12 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal12.sorted.bam OUTPUT=Mal12.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal12.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal12
rm Mal12.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal12 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal12.dupl_rm.bam OUTPUT=Mal12.bam RGID=Mal12 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal12;

rm -rf temp.Mal12
rm Mal12.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal12.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal12.bam > Mal12.stats
