#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal19.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal19.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/Mal19.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal19.sorted.bam Mal19.raw.bam

rm Mal19.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal19 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal19.sorted.bam OUTPUT=Mal19.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal19.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal19
rm Mal19.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal19 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal19.dupl_rm.bam OUTPUT=Mal19.bam RGID=Mal19 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal19;

rm -rf temp.Mal19
rm Mal19.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal19.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal19.bam > Mal19.stats
