#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/331a.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/331a.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/331a.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o 331a.sorted.bam 331a.raw.bam

rm 331a.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.331a -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=331a.sorted.bam OUTPUT=331a.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=331a.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.331a
rm 331a.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.331a -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=331a.dupl_rm.bam OUTPUT=331a.bam RGID=331a RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=331a;

rm -rf temp.331a
rm 331a.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 331a.bam
/home/knam/save/programs/samtools-1.9/samtools stats 331a.bam > 331a.stats
