#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal22.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal22.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/Mal22.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal22.sorted.bam Mal22.raw.bam

rm Mal22.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal22 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal22.sorted.bam OUTPUT=Mal22.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal22.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal22
rm Mal22.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal22 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal22.dupl_rm.bam OUTPUT=Mal22.bam RGID=Mal22 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal22;

rm -rf temp.Mal22
rm Mal22.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal22.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal22.bam > Mal22.stats
