#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal2sb.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal2sb.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/Mal2sb.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal2sb.sorted.bam Mal2sb.raw.bam

rm Mal2sb.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal2sb -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal2sb.sorted.bam OUTPUT=Mal2sb.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal2sb.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal2sb
rm Mal2sb.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal2sb -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal2sb.dupl_rm.bam OUTPUT=Mal2sb.bam RGID=Mal2sb RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal2sb;

rm -rf temp.Mal2sb
rm Mal2sb.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal2sb.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal2sb.bam > Mal2sb.stats
