#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal32.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal32.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/Mal32.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal32.sorted.bam Mal32.raw.bam

rm Mal32.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal32 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal32.sorted.bam OUTPUT=Mal32.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal32.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal32
rm Mal32.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal32 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal32.dupl_rm.bam OUTPUT=Mal32.bam RGID=Mal32 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal32;

rm -rf temp.Mal32
rm Mal32.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal32.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal32.bam > Mal32.stats
