#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/334A.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/334A.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/334A.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o 334A.sorted.bam 334A.raw.bam

rm 334A.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.334A -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=334A.sorted.bam OUTPUT=334A.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=334A.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.334A
rm 334A.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.334A -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=334A.dupl_rm.bam OUTPUT=334A.bam RGID=334A RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=334A;

rm -rf temp.334A
rm 334A.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 334A.bam
/home/knam/save/programs/samtools-1.9/samtools stats 334A.bam > 334A.stats
