#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal47.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/Mal47.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/Mal47.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o Mal47.sorted.bam Mal47.raw.bam

rm Mal47.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal47 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=Mal47.sorted.bam OUTPUT=Mal47.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=Mal47.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.Mal47
rm Mal47.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.Mal47 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=Mal47.dupl_rm.bam OUTPUT=Mal47.bam RGID=Mal47 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=Mal47;

rm -rf temp.Mal47
rm Mal47.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index Mal47.bam
/home/knam/save/programs/samtools-1.9/samtools stats Mal47.bam > Mal47.stats
