#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/rCC1.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/rCC1.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/rCC1.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o rCC1.sorted.bam rCC1.raw.bam

rm rCC1.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.rCC1 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=rCC1.sorted.bam OUTPUT=rCC1.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=rCC1.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.rCC1
rm rCC1.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.rCC1 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=rCC1.dupl_rm.bam OUTPUT=rCC1.bam RGID=rCC1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=rCC1;

rm -rf temp.rCC1
rm rCC1.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index rCC1.bam
/home/knam/save/programs/samtools-1.9/samtools stats rCC1.bam > rCC1.stats
