#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/rCC20.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/rCC20.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/rCC20.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o rCC20.sorted.bam rCC20.raw.bam

rm rCC20.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.rCC20 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=rCC20.sorted.bam OUTPUT=rCC20.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=rCC20.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.rCC20
rm rCC20.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.rCC20 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=rCC20.dupl_rm.bam OUTPUT=rCC20.bam RGID=rCC20 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=rCC20;

rm -rf temp.rCC20
rm rCC20.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index rCC20.bam
/home/knam/save/programs/samtools-1.9/samtools stats rCC20.bam > rCC20.stats
