#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/rCC25.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/rCC25.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/rCC25.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o rCC25.sorted.bam rCC25.raw.bam

rm rCC25.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.rCC25 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=rCC25.sorted.bam OUTPUT=rCC25.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=rCC25.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.rCC25
rm rCC25.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.rCC25 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=rCC25.dupl_rm.bam OUTPUT=rCC25.bam RGID=rCC25 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=rCC25;

rm -rf temp.rCC25
rm rCC25.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index rCC25.bam
/home/knam/save/programs/samtools-1.9/samtools stats rCC25.bam > rCC25.stats
