#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/345K.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/345K.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/345K.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o 345K.sorted.bam 345K.raw.bam

rm 345K.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.345K -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=345K.sorted.bam OUTPUT=345K.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=345K.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.345K
rm 345K.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.345K -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=345K.dupl_rm.bam OUTPUT=345K.bam RGID=345K RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=345K;

rm -rf temp.345K
rm 345K.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 345K.bam
/home/knam/save/programs/samtools-1.9/samtools stats 345K.bam > 345K.stats
