#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/sfrugi_AUS/processed/346M.pair1.truncated.gz -2 /home/knam/work/processing_fq/sfrugi_AUS/processed/346M.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.3/346M.raw.bam

cd ../bam.3

/home/knam/save/programs/samtools-1.9/samtools sort -o 346M.sorted.bam 346M.raw.bam

rm 346M.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.346M -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=346M.sorted.bam OUTPUT=346M.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=346M.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.346M
rm 346M.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.346M -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=346M.dupl_rm.bam OUTPUT=346M.bam RGID=346M RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=346M;

rm -rf temp.346M
rm 346M.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index 346M.bam
/home/knam/save/programs/samtools-1.9/samtools stats 346M.bam > 346M.stats
