#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH10/ACH10.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH10/ACH10.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH10.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH10.sorted.bam ACH10.raw.bam

rm ACH10.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH10 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH10.sorted.bam OUTPUT=ACH10.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH10.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH10
rm ACH10.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH10 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH10.dupl_rm.bam OUTPUT=ACH10.bam RGID=ACH10 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH10;

rm -rf temp.ACH10
rm ACH10.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH10.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH10.bam > ACH10.stats
