#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH22/ACH22.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH22/ACH22.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH22.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH22.sorted.bam ACH22.raw.bam

rm ACH22.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH22 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH22.sorted.bam OUTPUT=ACH22.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH22.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH22
rm ACH22.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH22 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH22.dupl_rm.bam OUTPUT=ACH22.bam RGID=ACH22 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH22;

rm -rf temp.ACH22
rm ACH22.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH22.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH22.bam > ACH22.stats
