#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH37/ACH37.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH37/ACH37.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH37.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH37.sorted.bam ACH37.raw.bam

rm ACH37.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH37 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH37.sorted.bam OUTPUT=ACH37.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH37.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH37
rm ACH37.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH37 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH37.dupl_rm.bam OUTPUT=ACH37.bam RGID=ACH37 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH37;

rm -rf temp.ACH37
rm ACH37.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH37.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH37.bam > ACH37.stats
