#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH20/ACH20.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH20/ACH20.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH20.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH20.sorted.bam ACH20.raw.bam

rm ACH20.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH20 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH20.sorted.bam OUTPUT=ACH20.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH20.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH20
rm ACH20.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH20 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH20.dupl_rm.bam OUTPUT=ACH20.bam RGID=ACH20 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH20;

rm -rf temp.ACH20
rm ACH20.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH20.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH20.bam > ACH20.stats
