#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH6/ACH6.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH6/ACH6.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH6.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH6.sorted.bam ACH6.raw.bam

rm ACH6.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH6 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH6.sorted.bam OUTPUT=ACH6.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH6.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH6
rm ACH6.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH6 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH6.dupl_rm.bam OUTPUT=ACH6.bam RGID=ACH6 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH6;

rm -rf temp.ACH6
rm ACH6.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH6.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH6.bam > ACH6.stats
