#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH9/ACH9.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH9/ACH9.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH9.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH9.sorted.bam ACH9.raw.bam

rm ACH9.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH9 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH9.sorted.bam OUTPUT=ACH9.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH9.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH9
rm ACH9.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH9 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH9.dupl_rm.bam OUTPUT=ACH9.bam RGID=ACH9 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH9;

rm -rf temp.ACH9
rm ACH9.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH9.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH9.bam > ACH9.stats
