#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH17/ACH17.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH17/ACH17.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH17.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH17.sorted.bam ACH17.raw.bam

rm ACH17.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH17 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH17.sorted.bam OUTPUT=ACH17.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH17.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH17
rm ACH17.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH17 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH17.dupl_rm.bam OUTPUT=ACH17.bam RGID=ACH17 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH17;

rm -rf temp.ACH17
rm ACH17.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH17.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH17.bam > ACH17.stats
