#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH4/ACH4.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH4/ACH4.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH4.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH4.sorted.bam ACH4.raw.bam

rm ACH4.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH4 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH4.sorted.bam OUTPUT=ACH4.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH4.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH4
rm ACH4.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH4 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH4.dupl_rm.bam OUTPUT=ACH4.bam RGID=ACH4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH4;

rm -rf temp.ACH4
rm ACH4.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH4.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH4.bam > ACH4.stats
