#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH21/ACH21.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH21/ACH21.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH21.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH21.sorted.bam ACH21.raw.bam

rm ACH21.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH21 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH21.sorted.bam OUTPUT=ACH21.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH21.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH21
rm ACH21.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH21 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH21.dupl_rm.bam OUTPUT=ACH21.bam RGID=ACH21 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH21;

rm -rf temp.ACH21
rm ACH21.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH21.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH21.bam > ACH21.stats
