#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH16/ACH16.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH16/ACH16.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH16.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH16.sorted.bam ACH16.raw.bam

rm ACH16.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH16 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH16.sorted.bam OUTPUT=ACH16.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH16.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH16
rm ACH16.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH16 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH16.dupl_rm.bam OUTPUT=ACH16.bam RGID=ACH16 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH16;

rm -rf temp.ACH16
rm ACH16.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH16.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH16.bam > ACH16.stats
