#!/bin/bash
#SBATCH --mem=20G

cd /home/knam/work/sfrugiperda_SNP/mt/ref

/home/knam/save/programs/bowtie2-2.3.4.1-linux-x86_64/bowtie2 -x sfmt -1 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH38/ACH38.pair1.truncated.gz -2 /home/knam/work/processing_fq/laneseq_201909/processed/ACH/ACH38/ACH38.pair2.truncated.gz | /home/knam/save/programs/samtools-1.9/samtools view -F 4 -b -h -o ../bam.4/ACH38.raw.bam

cd ../bam.4

/home/knam/save/programs/samtools-1.9/samtools sort -o ACH38.sorted.bam ACH38.raw.bam

rm ACH38.raw.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH38 -jar /home/knam/save/programs/picard.jar MarkDuplicates INPUT=ACH38.sorted.bam OUTPUT=ACH38.dupl_rm.bam REMOVE_DUPLICATES=true METRICS_FILE=ACH38.metricN.log ASSUME_SORTED=True MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 

rm -rf temp.ACH38
rm ACH38.sorted.bam

java -Xmx4g -Djava.io.tmpdir=temp.ACH38 -jar /home/knam/save/programs/picard.jar AddOrReplaceReadGroups INPUT=ACH38.dupl_rm.bam OUTPUT=ACH38.bam RGID=ACH38 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=ACH38;

rm -rf temp.ACH38
rm ACH38.dupl_rm.bam

/home/knam/save/programs/samtools-1.9/samtools index ACH38.bam
/home/knam/save/programs/samtools-1.9/samtools stats ACH38.bam > ACH38.stats
