#!/bin/bash
#SBATCH --mem=100G
#SBATCH -p unlimitq
#SBATCH -c 4

cd /home/knam/work/sfrugiperda_SNP/nuc_4/gvcf

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/nuc_1/ref/sfC.ver7.fa -I ../bam/ACH33.bam -O ACH33.g.vcf.gz -ERC GVCF
