#!/bin/bash
#SBATCH -c 4
#SBATCH --mem=200G

cd /home/knam/work/sfrugiperda_SNP/nuc_4/gvcf

/home/knam/save/programs/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/knam/work/sfrugiperda_SNP/nuc_1/ref/sfC.ver7.fa -I ../bam/ACH31.bam -O ACH31.g.vcf.gz -ERC GVCF
