#!/bin/bash

cd /home/kiwoong/Desktop/sfrugiperda_SNP/nuc_4/gvcf

/home/kiwoong/bioinformatics/gatk-4.1.2.0/gatk HaplotypeCaller -R /home/kiwoong/Desktop/sfrugiperda_SNP/nuc_2/ref/sfC.ver7.fa -I /media/kiwoong/DATA/L01.bam -O L01.g.vcf.gz -ERC GVCF






